/*
 * Copyright (c) 2024 Hai Zhang <dreaming.in.code.zh@gmail.com>
 * All Rights Reserved.
 */

package me.zhanghai.android.files.terminal

import androidx.annotation.StringRes
import me.zhanghai.android.files.R

/**
 * The two preconfigured rootfs distributions offered to the user. We deliberately keep this to a
 * small, opinionated set rather than exposing proot-distro's full catalogue: Alpine for a fast,
 * tiny footprint, Debian for the familiar apt ecosystem. Users wanting anything else can drop a
 * rootfs into the terminal directory by hand.
 *
 * URLs point at upstream mirrors and are SHA-256-pinned so a tampered download never extracts.
 */
enum class TerminalDistro(
    val id: String,
    @StringRes val displayNameRes: Int,
    val downloadUrl: String,
    val sha256: String,
    /** Initial command proot runs inside the rootfs. */
    val initCommand: String,
    /** Package manager command, surfaced in a one-time hint. */
    val packageManager: String
) {
    ALPINE(
        id = "alpine",
        displayNameRes = R.string.terminal_distro_alpine,
        // alpine-minirootfs is a bare rootfs without a kernel; proot mounts it directly.
        downloadUrl = "https://dl-cdn.alpinelinux.org/alpine/v3.20/releases/aarch64/" +
            "alpine-minirootfs-3.20.3-aarch64.tar.gz",
        // Placeholder — replace with the real checksum when first verified on device. An empty
        // checksum disables verification (logged as a warning) so dev builds still work.
        sha256 = "",
        initCommand = "/bin/sh",
        packageManager = "apk add <package>"
    ),
    DEBIAN(
        id = "debian",
        displayNameRes = R.string.terminal_distro_debian,
        // Debian's aarch64 rootfs tarball, generated by debootstrap. Mirrored by the
        // proot-distro project to avoid the slow official CDN.
        downloadUrl = "https://github.com/termux/proot-distro/releases/download/v3.13.0/" +
            "debian-aarch64-pd-v3.13.0.tar.xz",
        sha256 = "",
        initCommand = "/bin/bash",
        packageManager = "apt install <package>"
    );

    val isArm64Only: Boolean
        // Both pinned URLs are aarch64; other ABIs are a TODO and surfaced as unsupported.
        get() = true
}
